version: "3.9"

services:

  django:
    build: .
    command: sh -c "python manage.py migrate --settings=djmil.settings_files.settings
      && python manage.py runserver 0.0.0.0:8000 --settings=djmil.settings_files.settings
      "

    ports:
      - '8000:8000'
    depends_on:
      - pgdb
      - redis



  pgdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: vidma
      POSTGRES_USER: djmil_admin
      POSTGRES_PASSWORD: 12345
    ports:
      - '5432:5432'
    container_name: pgdb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"











