version: "3.9"

services:

  django:
    build: .
    command: sh -c "python manage.py migrate --settings=djmil.settings_files.settings        
      &&  python manage.py runserver 0.0.0.0:8000 --settings=djmil.settings_files.settings
      "

    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - '8000:8000'
    depends_on:
      - pgdb
      - redis




  pgdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: vidma
      POSTGRES_USER: djmil_admin
      POSTGRES_PASSWORD: 12345
    ports:
      - '5432:5432'
    container_name: pgdb


  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - pgdb



















