# Generated by Django 4.1.7 on 2023-03-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('dt_first', models.DateTimeField(blank=True, null=True)),
                ('dt_last', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MainOrders',
                'verbose_name_plural': 'MainOrders',
            },
        ),
    ]
