# Generated by Django 4.1.7 on 2023-04-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('dt_first', models.DateTimeField(blank=True, null=True)),
                ('dt_last', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MainOrders',
                'verbose_name_plural': 'MainOrders',
            },
        ),
        migrations.CreateModel(
            name='SecondOrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=16)),
                ('product_type', models.IntegerField()),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=45)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('phone_app_latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True)),
                ('phone_app_longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True)),
                ('home_latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True)),
                ('home_longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True)),
                ('dt', models.DateTimeField()),
                ('frame_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SecondOrdersModel',
                'verbose_name_plural': 'SecondOrdersModel',
            },
        ),
    ]
