# Generated by Django 4.1.7 on 2023-03-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_djmil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainorders',
            name='id_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
