# Generated by Django 4.1.7 on 2023-03-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_djmil', '0003_remove_mainorders_id_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondOrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=16)),
                ('product_type', models.IntegerField()),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=45)),
                ('height', models.IntegerField(blank=True, max_length=20, null=True)),
                ('altitude', models.IntegerField(blank=True, max_length=20)),
                ('phone_app_latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True)),
                ('phone_app_longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True)),
                ('home_latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True)),
                ('home_longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True)),
                ('dt', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'SecondOrdersModel',
                'verbose_name_plural': 'SecondOrdersModel',
            },
        ),
    ]
