# Generated by Django 4.1.7 on 2023-03-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_djmil', '0004_secondordersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondordersmodel',
            name='altitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondordersmodel',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
