# Generated by Django 4.1.7 on 2023-03-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_djmil', '0005_alter_secondordersmodel_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondordersmodel',
            name='frame_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
